config/routes.rb
Rails.application.routes.draw do

  get 'forms/confirmation'
  get 'completed_forms/keg' => 'completed_forms#keg'
  get 'completed_forms/kitchen' => 'completed_forms#kitchen'
  get 'completed_forms/restroom' => 'completed_forms#restroom'
  get 'completed_forms/today' => 'completed_forms#today'
  get 'completed_forms/week' => 'completed_forms#week'
  get 'completed_forms/month' => 'completed_forms#month'
  get 'completed_forms/keg_today' => 'completed_forms#keg_today'
  get 'completed_forms/keg_week' => 'completed_forms#keg_week'
  get 'completed_forms/keg_month' => 'completed_forms#keg_month'
  get 'completed_forms/kitchen_today' => 'completed_forms#kitchen_today'
  get 'completed_forms/kitchen_week' => 'completed_forms#kitchen_week'
  get 'completed_forms/kitchen_month' => 'completed_forms#kitchen_month'
  get 'completed_forms/restroom_today' => 'completed_forms#restroom_today'
  get 'completed_forms/restroom_week' => 'completed_forms#restroom_week'
  get 'completed_forms/restroom_month' => 'completed_forms#restroom_month'

  resources :forms
  resources :completed_forms
  resources :employees

  get 'beacons' => 'beacons#index'

  get 'graphs' => 'graphs#index'

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api do
    get 'forms' => 'forms#index'
    post 'sessions' => 'sessions#create'
    put 'beacons' => 'beacons#update'
    delete 'beacons' => 'beacons#destroy'
  end

  get '/completed_forms/refresh/:id' => 'completed_forms#refresh'

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  has_many :forms
  belongs_to :employee


  def time_format
  	#need to make the time format better
  	self.updated_at.strftime('%l:%M%P')
  end

  def date_format
  	self.updated_at.strftime('%m/%e/%y')
  end

  def beacon_time_stamp
  	time_format + " " + 'on' + " " + date_format
  end
end

app/controllers/api/beacons_controller.rb
class Api::BeaconsController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def update
    beacon = Beacon.find_by(minor: params[:minor_id])
    beacon.update!(employee_id: params[:employee_id])
    head :ok
  end

  def destroy
    beacon = Beacon.find_by(minor: params[:minor_id])
    beacon.update!(employee_id: nil)
    head :ok
  end
end

# TEST ENTER REGION
=begin
curl -XPUT -H "Content-Type: application/json" "localhost:3000/api/beacons" -d '
{
  "minor_id": "2",
  "employee_id": "1"
}'
=end

# TEST EXIT REGION
=begin
curl -XDELETE -H "Content-Type: application/json" "localhost:3000/api/beacons" -d '
{
  "minor_id": "2",
  "employee_id": "1"
}'
=end

# TEST ENTER REGION on HEROKU
=begin
curl -XPUT -H "Content-Type: application/json" "http://qaware.herokuapp.com/api/beacons" -d '
{
  "minor_id": "2",
  "employee_id": "1"
}'
=end

# TEST EXIT REGION on HEROKU
=begin
curl -XDELETE -H "Content-Type: application/json" "http://qaware.herokuapp.com/api/beacons" -d '
{
  "minor_id": "2",
  "employee_id": "1"
}'
=end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  def index
    @beacons = Beacon.all
    @completed_forms = CompletedForm.all
    @forms = Form.all
  end
end

app/views/beacons/index.html.erb
<div class="container">

  <%= render :partial => 'welcome/buttons' %>

  <div class="beacon_index">
    <table class="table beacons" >
    <h2 class= "forms_header">Inspection Locations</h2>
      <tr>
        <th>Name</th>
        <th>Current Employee</th>
        <th>Last Updated</th>
      </tr>
      <% @beacons.each do |beacon| %>
          <tr class="beacon">
            <td><%= beacon.location %></td>
            <td><%= beacon.employee ? beacon.employee.name : "No employee information" %></td>
            <td><%= beacon.beacon_time_stamp %></td>
          </tr>
      <% end %>
    </table>
  </div>

  <div class="completed_form_totals">
    <table class="table totals">
      <thead>
        <tr>
          <th></th>
          <th><%= link_to "Today", completed_forms_today_path %></th>
          <th><%= link_to "Week", completed_forms_week_path %></th>
          <th><%= link_to "Month", completed_forms_month_path %></th>
        </tr>
      </thead>
      <div class="data_totals">
        <tr>
          <th><%= link_to "#{@forms.find(1).title}", completed_forms_keg_path %></th>
          <th><%= link_to "#{@completed_forms.today(1).size}", completed_forms_keg_today_path %></th>
          <th><%= link_to "#{@completed_forms.this_week(1).size}", completed_forms_keg_week_path %></th>
          <th><%= link_to "#{@completed_forms.this_month(1).size}", completed_forms_keg_month_path %></th>
        </tr>
        <tr>
          <th><%= link_to "#{@forms.find(2).title}", completed_forms_kitchen_path %></th>
          <th><%= link_to "#{@completed_forms.today(2).size}", completed_forms_kitchen_today_path %></th>
          <th><%= link_to "#{@completed_forms.this_week(2).size}", completed_forms_kitchen_week_path %></th>
          <th><%= link_to "#{@completed_forms.this_month(2).size}", completed_forms_kitchen_month_path %></th>
        </tr>
        <tr>
          <th><%= link_to "#{@forms.find(3).title}", completed_forms_restroom_path %></th>
          <th><%= link_to "#{@completed_forms.today(3).size}", completed_forms_restroom_today_path %></th>
          <th><%= link_to "#{@completed_forms.this_week(3).size}", completed_forms_restroom_week_path %></th>
          <th><%= link_to "#{@completed_forms.this_month(3).size}", completed_forms_restroom_month_path %></th>
        </tr>
        <tr>
          <th><%= link_to "Total", completed_forms_path %></th>
          <th><%= link_to "#{@completed_forms.total_today.size}", completed_forms_today_path %></th>
          <th><%= link_to "#{@completed_forms.total_this_week.size}", completed_forms_week_path %></th>
          <th><%= link_to "#{@completed_forms.total_this_month.size}", completed_forms_month_path %></th>
        </tr>
      </div>
    </table>
  </div>

</div>