config/routes.rb
Rails.application.routes.draw do

  get 'forms/confirmation'
  get 'completed_forms/keg' => 'completed_forms#keg'
  get 'completed_forms/kitchen' => 'completed_forms#kitchen'
  get 'completed_forms/restroom' => 'completed_forms#restroom'
  get 'completed_forms/today' => 'completed_forms#today'
  get 'completed_forms/week' => 'completed_forms#week'
  get 'completed_forms/month' => 'completed_forms#month'
  get 'completed_forms/keg_today' => 'completed_forms#keg_today'
  get 'completed_forms/keg_week' => 'completed_forms#keg_week'
  get 'completed_forms/keg_month' => 'completed_forms#keg_month'
  get 'completed_forms/kitchen_today' => 'completed_forms#kitchen_today'
  get 'completed_forms/kitchen_week' => 'completed_forms#kitchen_week'
  get 'completed_forms/kitchen_month' => 'completed_forms#kitchen_month'
  get 'completed_forms/restroom_today' => 'completed_forms#restroom_today'
  get 'completed_forms/restroom_week' => 'completed_forms#restroom_week'
  get 'completed_forms/restroom_month' => 'completed_forms#restroom_month'

  resources :forms
  resources :completed_forms
  resources :employees

  get 'beacons' => 'beacons#index'

  get 'graphs' => 'graphs#index'

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api do
    get 'forms' => 'forms#index'
    post 'sessions' => 'sessions#create'
    put 'beacons' => 'beacons#update'
    delete 'beacons' => 'beacons#destroy'
  end

  get '/completed_forms/refresh/:id' => 'completed_forms#refresh'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to login_path
  end
end

app/views/welcome/_buttons.html.erb
<div class="link_buttons">
    <h4>
      <%= link_to "Location Status", beacons_path, class: "btn btn-hg btn-primary" %>
      <%= link_to "Completed Inspections", completed_forms_path, class: "btn btn-hg btn-primary" %>
      <%= link_to "View Employees", employees_path, class: "btn btn-hg btn-primary" %>
      <%= link_to "View Graphs", graphs_path, class: "btn btn-hg btn-primary" %>
    </h4>
  </div>