config/routes.rb
Rails.application.routes.draw do

  get 'forms/confirmation'
  get 'completed_forms/keg' => 'completed_forms#keg'
  get 'completed_forms/kitchen' => 'completed_forms#kitchen'
  get 'completed_forms/restroom' => 'completed_forms#restroom'
  get 'completed_forms/today' => 'completed_forms#today'
  get 'completed_forms/week' => 'completed_forms#week'
  get 'completed_forms/month' => 'completed_forms#month'
  get 'completed_forms/keg_today' => 'completed_forms#keg_today'
  get 'completed_forms/keg_week' => 'completed_forms#keg_week'
  get 'completed_forms/keg_month' => 'completed_forms#keg_month'
  get 'completed_forms/kitchen_today' => 'completed_forms#kitchen_today'
  get 'completed_forms/kitchen_week' => 'completed_forms#kitchen_week'
  get 'completed_forms/kitchen_month' => 'completed_forms#kitchen_month'
  get 'completed_forms/restroom_today' => 'completed_forms#restroom_today'
  get 'completed_forms/restroom_week' => 'completed_forms#restroom_week'
  get 'completed_forms/restroom_month' => 'completed_forms#restroom_month'

  resources :forms
  resources :completed_forms
  resources :employees

  get 'beacons' => 'beacons#index'

  get 'graphs' => 'graphs#index'

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api do
    get 'forms' => 'forms#index'
    post 'sessions' => 'sessions#create'
    put 'beacons' => 'beacons#update'
    delete 'beacons' => 'beacons#destroy'
  end

  get '/completed_forms/refresh/:id' => 'completed_forms#refresh'

end

app/controllers/api/forms_controller.rb
class Api::FormsController < ApplicationController
  def index
    forms = Form.all
    render json: forms.to_json(include: :beacon)
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  def index
    @forms = Form.all
  end

  def show
    @empty_form = Form.find(params[:id])
    @employees = Employee.all
  end
end

app/views/forms/confirmation.html.erb
<div class='confirmation'>
  <h1>QAware</h1><br>
  <h3>Successfully submitted</h3>
  <h2>Thanks!</h2>
</div>

app/views/forms/index.html.erb
<div class="page">
  <div class="welcomepage">
    <h1>QAware</h1><br>
    <% @forms.each do |form| %>
      <h3>
        <%= link_to "#{form.title}", form_path(form), class: 'button' %><br><br>
      </h3>
    <% end %>
  </div>
</div>

app/views/forms/show.html.erb
<div class='page_show'>
 <div class="new_form">
  <h2><%= @empty_form.title %></h2>

    <form id="empty_form" action="/completed_forms" method="post">

      <label>
        <select class="button_hidden" name="response[employee_id]">
          <% @employees.each do |employee| %>
          <option value="<%= employee.id %>">
            <%=employee.name%>
          </option>
          <% end %><br>
        </select>
      </label><br>

      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="response[form_id]"value="<%= @empty_form.id %>">
      <ol>
        <% @empty_form.questions.each do |question| %>
          <li><%= question.text %></li>
            <% question.possible_responses.each do |possible_response| %>
            <li><input type="radio" name="responses[<%=question.id%>]" value="<%= possible_response.id %>"> <%=possible_response.text%></li>
            <% end %>
            <br>
        <% end %>

        <input class="button" type="submit" value="Submit">
      </ol>
    </form>
  </div>
</div>