config/routes.rb
Rails.application.routes.draw do

  get 'forms/confirmation'
  get 'completed_forms/keg' => 'completed_forms#keg'
  get 'completed_forms/kitchen' => 'completed_forms#kitchen'
  get 'completed_forms/restroom' => 'completed_forms#restroom'
  get 'completed_forms/today' => 'completed_forms#today'
  get 'completed_forms/week' => 'completed_forms#week'
  get 'completed_forms/month' => 'completed_forms#month'
  get 'completed_forms/keg_today' => 'completed_forms#keg_today'
  get 'completed_forms/keg_week' => 'completed_forms#keg_week'
  get 'completed_forms/keg_month' => 'completed_forms#keg_month'
  get 'completed_forms/kitchen_today' => 'completed_forms#kitchen_today'
  get 'completed_forms/kitchen_week' => 'completed_forms#kitchen_week'
  get 'completed_forms/kitchen_month' => 'completed_forms#kitchen_month'
  get 'completed_forms/restroom_today' => 'completed_forms#restroom_today'
  get 'completed_forms/restroom_week' => 'completed_forms#restroom_week'
  get 'completed_forms/restroom_month' => 'completed_forms#restroom_month'

  resources :forms
  resources :completed_forms
  resources :employees

  get 'beacons' => 'beacons#index'

  get 'graphs' => 'graphs#index'

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  namespace :api do
    get 'forms' => 'forms#index'
    post 'sessions' => 'sessions#create'
    put 'beacons' => 'beacons#update'
    delete 'beacons' => 'beacons#destroy'
  end

  get '/completed_forms/refresh/:id' => 'completed_forms#refresh'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qaware</title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.17.2/build/cssreset/cssreset-min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body>
    <% if session[:manager_id] %>
      <nav class="navbar">
          <div>
            <%= image_tag "logos/logo.png", class: "navbar-header" %>
            <span>
              <%#= link_to "Forms", forms_path, class: "btn btn-default" %>
              <%= link_to "Log Out",  logout_path, class: "btn btn-default"%>
            </span>
          </div>
      </nav>
    <% end %>

<%= yield %>

</body>
</html>